### ISSUE TITLE
Respository Name and application name conflicts

### ISSUE THREAD

**Issue by marutha** [tonyg/erlang-rfc4627#12]
Hi,

This is not a critical bug, but just a information when I tried to add this as dependency  with repository name "erlang-rfc4627" to my rebar.config of my project it raised me the below error.

``` erlang
Pulling "erlang-rfc4627" from {git,"git://github.com/marutha/erlang-rfc4627.git",
                                    "master"}
Initialized empty Git repository in /rfc_test/deps/erlang-rfc4627/.git/
ERROR: Dependency dir /rfc_test/deps/erlang-rfc4627 failed application validation with reason:
{name_mismatch,{"/rfc_test/deps/erlang-rfc4627/ebin/rfc4627_jsonrpc.app",
                 {expected,"erlang-rfc4627"},
                {has,rfc4627_jsonrpc}}}.

ERROR: 'get-deps' failed while processing /rfc_test/: rebar_abort
```

after changing the value to rfc4627_jsonrpc in rebar config the error disappeared.

I guess either repository name has to be changed or some note on read me would be helpful for new users.

Thanks,
Marutha

**Comment by tonyg** [comment]
Hmm, thanks. If you could supply a suggested note for the readme that'd be very helpful. It'd be good if you could include an example of a broken rebar.config, a working rebar.config, and an explanation of what was wrong with the broken one. Thanks!

**Comment by marutha** [comment]
fixed in https://github.com/tonyg/erlang-rfc4627/issues/14
