### ISSUE TITLE
when using chinese

### ISSUE THREAD

**Issue by sorawa** [tonyg/erlang-rfc4627#18]
7> rfc4627:decode( " {\"user\":\"哈哈\"}" ).
*\* exception exit: {ucs,{bad_utf8_character_code}}
     in function  xmerl_ucs:from_utf8/1 (xmerl_ucs.erl, line 185)
     in call from rfc4627:unicode_decode/1 (lib/json/rfc4627.erl, line 323)
     in call from rfc4627:decode/1 (lib/json/rfc4627.erl, line 258)

**Comment by tonyg** [comment]
My guess is that the literal input there was not encoded in UTF-8. Here's what I see, with UTF-8 encoding:

``` erlang
Eshell V7.0  (abort with ^G)
1> "哈哈".
[229,147,136,229,147,136]
2> rfc4627:decode("{\"user\":\"哈哈\"}").
{ok,{obj,[{"user",<<229,147,136,229,147,136>>}]},[]}
```

I also wrote the string `{"user":"哈哈"}` into a file `t.json`, again using UTF-8 encoding, and then loaded it in and decoded it:

``` erlang
Eshell V7.0  (abort with ^G)
1> {ok, FileContents} = file:read_file("t.json").
{ok,<<123,34,117,115,101,114,34,58,34,229,147,136,229,
      147,136,34,125,10>>}
2> rfc4627:decode(FileContents).
{ok,{obj,[{"user",<<229,147,136,229,147,136>>}]},[]}
```

If you can't use UTF-8 for some reason, you might find `rfc4627:decode_noauto` useful, after decoding the input you have available into unicode _codepoints_ yourself:

``` erlang
Eshell V7.0  (abort with ^G)
1> "哈哈".
[21704,21704]
2> rfc4627:decode_noauto([123,34,117,115,101,114,34,58,34,21704,21704,34,125]).
{ok,{obj,[{"user",<<229,147,136,229,147,136>>}]},[]}
%% N.B. ................................................. ^^^^^ ^^^^^
```
