### ISSUE TITLE
deprecated tests...

### ISSUE THREAD

**Issue by adaptunit** [tonyg/erlang-rfc4627#4]
I read http://tonyg.github.com/erlang-rfc4627/doc/index.html  to try play with code...

> make all test-compile
> erlc -I include -o ebin -Dnew_inets -Wall +debug_info  test/test_jsonrpc_inets.erl test/test_rfc4627.erl
> test/test_jsonrpc_inets.erl:50: Warning: call to httpd:start/1 will fail, since it was removed in R14B; use inets:start/2,3

Eshell V5.8.4  (abort with ^G)
1>  test_jsonrpc_inets:start_httpd().
*\* exception error: undefined function httpd:start/1
     in function  test_jsonrpc_inets:start_httpd/0

I hope you find time to fix this little misunderstanding :)

**Comment by tonyg** [comment]
Thanks! Fixed by fd467939c4fef5233f4e60161775f63be5614fe2.
